// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcc.proto

package tcc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxStatus int32

const (
	TxStatus_Created   TxStatus = 0
	TxStatus_Confirmed TxStatus = 1
	TxStatus_Canceled  TxStatus = 2
	TxStatus_Timeout   TxStatus = 3
	TxStatus_Locked    TxStatus = 4
)

var TxStatus_name = map[int32]string{
	0: "Created",
	1: "Confirmed",
	2: "Canceled",
	3: "Timeout",
	4: "Locked",
}

var TxStatus_value = map[string]int32{
	"Created":   0,
	"Confirmed": 1,
	"Canceled":  2,
	"Timeout":   3,
	"Locked":    4,
}

func (x TxStatus) String() string {
	return proto.EnumName(TxStatus_name, int32(x))
}

func (TxStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{0}
}

type AgentCommand int32

const (
	AgentCommand_COMMMIT AgentCommand = 0
	AgentCommand_Cancel  AgentCommand = 1
)

var AgentCommand_name = map[int32]string{
	0: "COMMMIT",
	1: "Cancel",
}

var AgentCommand_value = map[string]int32{
	"COMMMIT": 0,
	"Cancel":  1,
}

func (x AgentCommand) String() string {
	return proto.EnumName(AgentCommand_name, int32(x))
}

func (AgentCommand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{1}
}

type NewTxRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTxRequest) Reset()         { *m = NewTxRequest{} }
func (m *NewTxRequest) String() string { return proto.CompactTextString(m) }
func (*NewTxRequest) ProtoMessage()    {}
func (*NewTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{0}
}

func (m *NewTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTxRequest.Unmarshal(m, b)
}
func (m *NewTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTxRequest.Marshal(b, m, deterministic)
}
func (m *NewTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTxRequest.Merge(m, src)
}
func (m *NewTxRequest) XXX_Size() int {
	return xxx_messageInfo_NewTxRequest.Size(m)
}
func (m *NewTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTxRequest proto.InternalMessageInfo

func (m *NewTxRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type NewTxResponse struct {
	Txid                 string   `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTxResponse) Reset()         { *m = NewTxResponse{} }
func (m *NewTxResponse) String() string { return proto.CompactTextString(m) }
func (*NewTxResponse) ProtoMessage()    {}
func (*NewTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{1}
}

func (m *NewTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTxResponse.Unmarshal(m, b)
}
func (m *NewTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTxResponse.Marshal(b, m, deterministic)
}
func (m *NewTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTxResponse.Merge(m, src)
}
func (m *NewTxResponse) XXX_Size() int {
	return xxx_messageInfo_NewTxResponse.Size(m)
}
func (m *NewTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTxResponse proto.InternalMessageInfo

func (m *NewTxResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type CommitTxRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTxRequest) Reset()         { *m = CommitTxRequest{} }
func (m *CommitTxRequest) String() string { return proto.CompactTextString(m) }
func (*CommitTxRequest) ProtoMessage()    {}
func (*CommitTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{2}
}

func (m *CommitTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTxRequest.Unmarshal(m, b)
}
func (m *CommitTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTxRequest.Marshal(b, m, deterministic)
}
func (m *CommitTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTxRequest.Merge(m, src)
}
func (m *CommitTxRequest) XXX_Size() int {
	return xxx_messageInfo_CommitTxRequest.Size(m)
}
func (m *CommitTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTxRequest proto.InternalMessageInfo

func (m *CommitTxRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type CommitTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTxResponse) Reset()         { *m = CommitTxResponse{} }
func (m *CommitTxResponse) String() string { return proto.CompactTextString(m) }
func (*CommitTxResponse) ProtoMessage()    {}
func (*CommitTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{3}
}

func (m *CommitTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTxResponse.Unmarshal(m, b)
}
func (m *CommitTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTxResponse.Marshal(b, m, deterministic)
}
func (m *CommitTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTxResponse.Merge(m, src)
}
func (m *CommitTxResponse) XXX_Size() int {
	return xxx_messageInfo_CommitTxResponse.Size(m)
}
func (m *CommitTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTxResponse proto.InternalMessageInfo

type CancelTxRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTxRequest) Reset()         { *m = CancelTxRequest{} }
func (m *CancelTxRequest) String() string { return proto.CompactTextString(m) }
func (*CancelTxRequest) ProtoMessage()    {}
func (*CancelTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{4}
}

func (m *CancelTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTxRequest.Unmarshal(m, b)
}
func (m *CancelTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTxRequest.Marshal(b, m, deterministic)
}
func (m *CancelTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTxRequest.Merge(m, src)
}
func (m *CancelTxRequest) XXX_Size() int {
	return xxx_messageInfo_CancelTxRequest.Size(m)
}
func (m *CancelTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTxRequest proto.InternalMessageInfo

func (m *CancelTxRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type CancelTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTxResponse) Reset()         { *m = CancelTxResponse{} }
func (m *CancelTxResponse) String() string { return proto.CompactTextString(m) }
func (*CancelTxResponse) ProtoMessage()    {}
func (*CancelTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{5}
}

func (m *CancelTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTxResponse.Unmarshal(m, b)
}
func (m *CancelTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTxResponse.Marshal(b, m, deterministic)
}
func (m *CancelTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTxResponse.Merge(m, src)
}
func (m *CancelTxResponse) XXX_Size() int {
	return xxx_messageInfo_CancelTxResponse.Size(m)
}
func (m *CancelTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTxResponse proto.InternalMessageInfo

type BeginLockResourceRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Rid                  string   `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Agent                string   `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	Resource             string   `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginLockResourceRequest) Reset()         { *m = BeginLockResourceRequest{} }
func (m *BeginLockResourceRequest) String() string { return proto.CompactTextString(m) }
func (*BeginLockResourceRequest) ProtoMessage()    {}
func (*BeginLockResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{6}
}

func (m *BeginLockResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginLockResourceRequest.Unmarshal(m, b)
}
func (m *BeginLockResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginLockResourceRequest.Marshal(b, m, deterministic)
}
func (m *BeginLockResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginLockResourceRequest.Merge(m, src)
}
func (m *BeginLockResourceRequest) XXX_Size() int {
	return xxx_messageInfo_BeginLockResourceRequest.Size(m)
}
func (m *BeginLockResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginLockResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginLockResourceRequest proto.InternalMessageInfo

func (m *BeginLockResourceRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *BeginLockResourceRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *BeginLockResourceRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *BeginLockResourceRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type BeginLockResourceRespose struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginLockResourceRespose) Reset()         { *m = BeginLockResourceRespose{} }
func (m *BeginLockResourceRespose) String() string { return proto.CompactTextString(m) }
func (*BeginLockResourceRespose) ProtoMessage()    {}
func (*BeginLockResourceRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{7}
}

func (m *BeginLockResourceRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginLockResourceRespose.Unmarshal(m, b)
}
func (m *BeginLockResourceRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginLockResourceRespose.Marshal(b, m, deterministic)
}
func (m *BeginLockResourceRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginLockResourceRespose.Merge(m, src)
}
func (m *BeginLockResourceRespose) XXX_Size() int {
	return xxx_messageInfo_BeginLockResourceRespose.Size(m)
}
func (m *BeginLockResourceRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginLockResourceRespose.DiscardUnknown(m)
}

var xxx_messageInfo_BeginLockResourceRespose proto.InternalMessageInfo

type EndLockResourceRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Rid                  string   `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Agent                string   `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	Resource             string   `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndLockResourceRequest) Reset()         { *m = EndLockResourceRequest{} }
func (m *EndLockResourceRequest) String() string { return proto.CompactTextString(m) }
func (*EndLockResourceRequest) ProtoMessage()    {}
func (*EndLockResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{8}
}

func (m *EndLockResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndLockResourceRequest.Unmarshal(m, b)
}
func (m *EndLockResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndLockResourceRequest.Marshal(b, m, deterministic)
}
func (m *EndLockResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndLockResourceRequest.Merge(m, src)
}
func (m *EndLockResourceRequest) XXX_Size() int {
	return xxx_messageInfo_EndLockResourceRequest.Size(m)
}
func (m *EndLockResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndLockResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndLockResourceRequest proto.InternalMessageInfo

func (m *EndLockResourceRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *EndLockResourceRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *EndLockResourceRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *EndLockResourceRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type EndLockResourceRespose struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndLockResourceRespose) Reset()         { *m = EndLockResourceRespose{} }
func (m *EndLockResourceRespose) String() string { return proto.CompactTextString(m) }
func (*EndLockResourceRespose) ProtoMessage()    {}
func (*EndLockResourceRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{9}
}

func (m *EndLockResourceRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndLockResourceRespose.Unmarshal(m, b)
}
func (m *EndLockResourceRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndLockResourceRespose.Marshal(b, m, deterministic)
}
func (m *EndLockResourceRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndLockResourceRespose.Merge(m, src)
}
func (m *EndLockResourceRespose) XXX_Size() int {
	return xxx_messageInfo_EndLockResourceRespose.Size(m)
}
func (m *EndLockResourceRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_EndLockResourceRespose.DiscardUnknown(m)
}

var xxx_messageInfo_EndLockResourceRespose proto.InternalMessageInfo

type AgentCommandRequest struct {
	Txid                 string       `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Resource             string       `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Command              AgentCommand `protobuf:"varint,3,opt,name=command,proto3,enum=tcc.AgentCommand" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AgentCommandRequest) Reset()         { *m = AgentCommandRequest{} }
func (m *AgentCommandRequest) String() string { return proto.CompactTextString(m) }
func (*AgentCommandRequest) ProtoMessage()    {}
func (*AgentCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{10}
}

func (m *AgentCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentCommandRequest.Unmarshal(m, b)
}
func (m *AgentCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentCommandRequest.Marshal(b, m, deterministic)
}
func (m *AgentCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentCommandRequest.Merge(m, src)
}
func (m *AgentCommandRequest) XXX_Size() int {
	return xxx_messageInfo_AgentCommandRequest.Size(m)
}
func (m *AgentCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentCommandRequest proto.InternalMessageInfo

func (m *AgentCommandRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *AgentCommandRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *AgentCommandRequest) GetCommand() AgentCommand {
	if m != nil {
		return m.Command
	}
	return AgentCommand_COMMMIT
}

type AttachAgentRequest struct {
	Agent                string   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachAgentRequest) Reset()         { *m = AttachAgentRequest{} }
func (m *AttachAgentRequest) String() string { return proto.CompactTextString(m) }
func (*AttachAgentRequest) ProtoMessage()    {}
func (*AttachAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{11}
}

func (m *AttachAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachAgentRequest.Unmarshal(m, b)
}
func (m *AttachAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachAgentRequest.Marshal(b, m, deterministic)
}
func (m *AttachAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachAgentRequest.Merge(m, src)
}
func (m *AttachAgentRequest) XXX_Size() int {
	return xxx_messageInfo_AttachAgentRequest.Size(m)
}
func (m *AttachAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachAgentRequest proto.InternalMessageInfo

func (m *AttachAgentRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

type ResourceStatusChangedRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Resource             string   `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Status               TxStatus `protobuf:"varint,3,opt,name=status,proto3,enum=tcc.TxStatus" json:"status,omitempty"`
	Agent                string   `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceStatusChangedRequest) Reset()         { *m = ResourceStatusChangedRequest{} }
func (m *ResourceStatusChangedRequest) String() string { return proto.CompactTextString(m) }
func (*ResourceStatusChangedRequest) ProtoMessage()    {}
func (*ResourceStatusChangedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{12}
}

func (m *ResourceStatusChangedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceStatusChangedRequest.Unmarshal(m, b)
}
func (m *ResourceStatusChangedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceStatusChangedRequest.Marshal(b, m, deterministic)
}
func (m *ResourceStatusChangedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceStatusChangedRequest.Merge(m, src)
}
func (m *ResourceStatusChangedRequest) XXX_Size() int {
	return xxx_messageInfo_ResourceStatusChangedRequest.Size(m)
}
func (m *ResourceStatusChangedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceStatusChangedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceStatusChangedRequest proto.InternalMessageInfo

func (m *ResourceStatusChangedRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *ResourceStatusChangedRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *ResourceStatusChangedRequest) GetStatus() TxStatus {
	if m != nil {
		return m.Status
	}
	return TxStatus_Created
}

func (m *ResourceStatusChangedRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

type ResourceStatusChangedRespose struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceStatusChangedRespose) Reset()         { *m = ResourceStatusChangedRespose{} }
func (m *ResourceStatusChangedRespose) String() string { return proto.CompactTextString(m) }
func (*ResourceStatusChangedRespose) ProtoMessage()    {}
func (*ResourceStatusChangedRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{13}
}

func (m *ResourceStatusChangedRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceStatusChangedRespose.Unmarshal(m, b)
}
func (m *ResourceStatusChangedRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceStatusChangedRespose.Marshal(b, m, deterministic)
}
func (m *ResourceStatusChangedRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceStatusChangedRespose.Merge(m, src)
}
func (m *ResourceStatusChangedRespose) XXX_Size() int {
	return xxx_messageInfo_ResourceStatusChangedRespose.Size(m)
}
func (m *ResourceStatusChangedRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceStatusChangedRespose.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceStatusChangedRespose proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("tcc.TxStatus", TxStatus_name, TxStatus_value)
	proto.RegisterEnum("tcc.AgentCommand", AgentCommand_name, AgentCommand_value)
	proto.RegisterType((*NewTxRequest)(nil), "tcc.NewTxRequest")
	proto.RegisterType((*NewTxResponse)(nil), "tcc.NewTxResponse")
	proto.RegisterType((*CommitTxRequest)(nil), "tcc.CommitTxRequest")
	proto.RegisterType((*CommitTxResponse)(nil), "tcc.CommitTxResponse")
	proto.RegisterType((*CancelTxRequest)(nil), "tcc.CancelTxRequest")
	proto.RegisterType((*CancelTxResponse)(nil), "tcc.CancelTxResponse")
	proto.RegisterType((*BeginLockResourceRequest)(nil), "tcc.BeginLockResourceRequest")
	proto.RegisterType((*BeginLockResourceRespose)(nil), "tcc.BeginLockResourceRespose")
	proto.RegisterType((*EndLockResourceRequest)(nil), "tcc.EndLockResourceRequest")
	proto.RegisterType((*EndLockResourceRespose)(nil), "tcc.EndLockResourceRespose")
	proto.RegisterType((*AgentCommandRequest)(nil), "tcc.AgentCommandRequest")
	proto.RegisterType((*AttachAgentRequest)(nil), "tcc.AttachAgentRequest")
	proto.RegisterType((*ResourceStatusChangedRequest)(nil), "tcc.ResourceStatusChangedRequest")
	proto.RegisterType((*ResourceStatusChangedRespose)(nil), "tcc.ResourceStatusChangedRespose")
}

func init() { proto.RegisterFile("tcc.proto", fileDescriptor_35dc7e9ebe8c6643) }

var fileDescriptor_35dc7e9ebe8c6643 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x93, 0xd4, 0x4d, 0xa6, 0x09, 0x75, 0x87, 0x16, 0x2c, 0x53, 0x2a, 0x30, 0xaa, 0x40,
	0x41, 0x4a, 0x51, 0x11, 0x3f, 0xa0, 0x89, 0x7a, 0x40, 0x10, 0x10, 0x21, 0x27, 0x24, 0x0e, 0xee,
	0x7a, 0x70, 0xac, 0xe2, 0xdd, 0x60, 0xaf, 0xd5, 0xfc, 0x07, 0x7e, 0x29, 0xff, 0x02, 0x79, 0xd7,
	0x76, 0x9d, 0x2f, 0x23, 0x71, 0xe8, 0xcd, 0xde, 0x79, 0xef, 0xcd, 0xf3, 0xec, 0x3c, 0x43, 0x47,
	0x32, 0x36, 0x98, 0xc7, 0x42, 0x0a, 0x6c, 0x4a, 0xc6, 0x5c, 0x17, 0xba, 0x9f, 0xe8, 0x76, 0xba,
	0x98, 0xd0, 0xaf, 0x94, 0x12, 0x89, 0x08, 0x2d, 0xb9, 0x08, 0x7d, 0xdb, 0x78, 0x66, 0xbc, 0xea,
	0x4c, 0xd4, 0xb3, 0xfb, 0x02, 0x7a, 0x39, 0x26, 0x99, 0x0b, 0x9e, 0x50, 0x09, 0x6a, 0x54, 0x40,
	0x67, 0x70, 0x30, 0x12, 0x51, 0x14, 0xca, 0x7a, 0x2d, 0x04, 0xeb, 0x0e, 0xa6, 0xe5, 0x14, 0xd5,
	0xe3, 0x8c, 0x7e, 0xfe, 0x9b, 0x5a, 0xc2, 0x72, 0x6a, 0x0c, 0xf6, 0x90, 0x82, 0x90, 0x7f, 0x14,
	0xec, 0x66, 0x42, 0x89, 0x48, 0x63, 0x46, 0x35, 0x1a, 0x68, 0x41, 0x33, 0x2e, 0x8d, 0x67, 0x8f,
	0x78, 0x04, 0xbb, 0x5e, 0x40, 0x5c, 0xda, 0x4d, 0x75, 0xa6, 0x5f, 0xd0, 0x81, 0x76, 0x9c, 0xcb,
	0xd9, 0x2d, 0x55, 0x28, 0xdf, 0x5d, 0x67, 0x63, 0xcf, 0x64, 0x2e, 0x12, 0x72, 0xe7, 0xf0, 0xe8,
	0x8a, 0xfb, 0xf7, 0xe9, 0xc6, 0xde, 0xd0, 0x51, 0x7b, 0x89, 0xe1, 0xe1, 0x65, 0x46, 0xcf, 0xe6,
	0xed, 0x71, 0xbf, 0xce, 0x48, 0xb5, 0x41, 0x63, 0xb9, 0x01, 0xbe, 0x86, 0x3d, 0xa6, 0x15, 0x94,
	0xa9, 0x07, 0x17, 0x87, 0x83, 0x6c, 0x87, 0x96, 0xa4, 0x0b, 0x84, 0xdb, 0x07, 0xbc, 0x94, 0xd2,
	0x63, 0x33, 0x55, 0x2e, 0x5a, 0x96, 0x5f, 0x65, 0x54, 0xbe, 0xca, 0xfd, 0x6d, 0xc0, 0x49, 0xe1,
	0xf9, 0xab, 0xf4, 0x64, 0x9a, 0x8c, 0x66, 0x1e, 0x0f, 0xe8, 0xbf, 0x9d, 0x9e, 0x81, 0x99, 0x28,
	0x9d, 0xdc, 0x68, 0x4f, 0x19, 0x9d, 0x2e, 0xb4, 0xf8, 0x24, 0x2f, 0xde, 0xb9, 0x69, 0x55, 0xdd,
	0x9c, 0x6e, 0x35, 0xa3, 0xa6, 0xd9, 0x1f, 0x43, 0xbb, 0x50, 0xc2, 0x7d, 0xd8, 0x1b, 0xc5, 0xe4,
	0x49, 0xf2, 0xad, 0x1d, 0xec, 0x41, 0x67, 0x24, 0xf8, 0x8f, 0x30, 0x8e, 0xc8, 0xb7, 0x0c, 0xec,
	0x42, 0x5b, 0x6f, 0x29, 0xf9, 0x56, 0x23, 0x43, 0x4e, 0xc3, 0x88, 0x44, 0x2a, 0xad, 0x26, 0x02,
	0x98, 0xd9, 0x3d, 0x91, 0x6f, 0xb5, 0xfa, 0x2f, 0xa1, 0x5b, 0x9d, 0xa0, 0x92, 0xfc, 0x3c, 0x1e,
	0x8f, 0xdf, 0x4f, 0xad, 0x9d, 0x0c, 0xa8, 0x35, 0x2c, 0xe3, 0xe2, 0x4f, 0x13, 0xcc, 0x2b, 0x1e,
	0x84, 0x9c, 0x70, 0x00, 0xbb, 0x2a, 0x87, 0xa8, 0x6f, 0xa0, 0x9a, 0x5b, 0x07, 0xab, 0x47, 0x79,
	0x4c, 0xdf, 0x81, 0xa9, 0xb3, 0x86, 0x47, 0xaa, 0xba, 0x92, 0x4f, 0xe7, 0x78, 0xe5, 0xb4, 0x42,
	0x53, 0xdd, 0x0b, 0xda, 0x72, 0x36, 0x0b, 0xda, 0x4a, 0x14, 0xf1, 0x0b, 0x1c, 0xae, 0xc5, 0x02,
	0x9f, 0x2a, 0xec, 0xb6, 0x88, 0x3a, 0x5b, 0xcb, 0x6a, 0xe6, 0xf8, 0x01, 0x0e, 0x56, 0x76, 0x1b,
	0x9f, 0x28, 0xc6, 0xe6, 0x8c, 0x39, 0x5b, 0x8a, 0x5a, 0xec, 0x3b, 0x1c, 0x6f, 0xbc, 0x60, 0x7c,
	0xae, 0x58, 0x75, 0x9b, 0xe8, 0xd4, 0x42, 0xb4, 0xfc, 0x10, 0xf6, 0x2b, 0x9b, 0x8f, 0x8f, 0x75,
	0x48, 0xd6, 0xb2, 0xe0, 0xd8, 0xeb, 0xe9, 0xd1, 0x95, 0x37, 0xc6, 0xf0, 0xf4, 0xdb, 0x49, 0x10,
	0xca, 0x59, 0x7a, 0x3d, 0x60, 0x22, 0x3a, 0x0f, 0x44, 0x44, 0xc9, 0x8c, 0x93, 0xbc, 0x15, 0xf1,
	0xcd, 0xb9, 0x64, 0xec, 0xda, 0x54, 0x3f, 0xee, 0xb7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x38,
	0x21, 0x62, 0x3e, 0xc5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EngineClient is the client API for Engine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EngineClient interface {
	NewTx(ctx context.Context, in *NewTxRequest, opts ...grpc.CallOption) (*NewTxResponse, error)
	Commit(ctx context.Context, in *CommitTxRequest, opts ...grpc.CallOption) (*CommitTxResponse, error)
	Cancel(ctx context.Context, in *CancelTxRequest, opts ...grpc.CallOption) (*CancelTxResponse, error)
	BeginLockResource(ctx context.Context, in *BeginLockResourceRequest, opts ...grpc.CallOption) (*BeginLockResourceRespose, error)
	EndLockResource(ctx context.Context, in *EndLockResourceRequest, opts ...grpc.CallOption) (*EndLockResourceRespose, error)
	ResourceStatusChanged(ctx context.Context, in *ResourceStatusChangedRequest, opts ...grpc.CallOption) (*ResourceStatusChangedRespose, error)
	AttachAgent(ctx context.Context, in *AttachAgentRequest, opts ...grpc.CallOption) (Engine_AttachAgentClient, error)
}

type engineClient struct {
	cc *grpc.ClientConn
}

func NewEngineClient(cc *grpc.ClientConn) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) NewTx(ctx context.Context, in *NewTxRequest, opts ...grpc.CallOption) (*NewTxResponse, error) {
	out := new(NewTxResponse)
	err := c.cc.Invoke(ctx, "/tcc.Engine/NewTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Commit(ctx context.Context, in *CommitTxRequest, opts ...grpc.CallOption) (*CommitTxResponse, error) {
	out := new(CommitTxResponse)
	err := c.cc.Invoke(ctx, "/tcc.Engine/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Cancel(ctx context.Context, in *CancelTxRequest, opts ...grpc.CallOption) (*CancelTxResponse, error) {
	out := new(CancelTxResponse)
	err := c.cc.Invoke(ctx, "/tcc.Engine/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) BeginLockResource(ctx context.Context, in *BeginLockResourceRequest, opts ...grpc.CallOption) (*BeginLockResourceRespose, error) {
	out := new(BeginLockResourceRespose)
	err := c.cc.Invoke(ctx, "/tcc.Engine/BeginLockResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) EndLockResource(ctx context.Context, in *EndLockResourceRequest, opts ...grpc.CallOption) (*EndLockResourceRespose, error) {
	out := new(EndLockResourceRespose)
	err := c.cc.Invoke(ctx, "/tcc.Engine/EndLockResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) ResourceStatusChanged(ctx context.Context, in *ResourceStatusChangedRequest, opts ...grpc.CallOption) (*ResourceStatusChangedRespose, error) {
	out := new(ResourceStatusChangedRespose)
	err := c.cc.Invoke(ctx, "/tcc.Engine/ResourceStatusChanged", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) AttachAgent(ctx context.Context, in *AttachAgentRequest, opts ...grpc.CallOption) (Engine_AttachAgentClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Engine_serviceDesc.Streams[0], "/tcc.Engine/AttachAgent", opts...)
	if err != nil {
		return nil, err
	}
	x := &engineAttachAgentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Engine_AttachAgentClient interface {
	Recv() (*AgentCommandRequest, error)
	grpc.ClientStream
}

type engineAttachAgentClient struct {
	grpc.ClientStream
}

func (x *engineAttachAgentClient) Recv() (*AgentCommandRequest, error) {
	m := new(AgentCommandRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EngineServer is the server API for Engine service.
type EngineServer interface {
	NewTx(context.Context, *NewTxRequest) (*NewTxResponse, error)
	Commit(context.Context, *CommitTxRequest) (*CommitTxResponse, error)
	Cancel(context.Context, *CancelTxRequest) (*CancelTxResponse, error)
	BeginLockResource(context.Context, *BeginLockResourceRequest) (*BeginLockResourceRespose, error)
	EndLockResource(context.Context, *EndLockResourceRequest) (*EndLockResourceRespose, error)
	ResourceStatusChanged(context.Context, *ResourceStatusChangedRequest) (*ResourceStatusChangedRespose, error)
	AttachAgent(*AttachAgentRequest, Engine_AttachAgentServer) error
}

func RegisterEngineServer(s *grpc.Server, srv EngineServer) {
	s.RegisterService(&_Engine_serviceDesc, srv)
}

func _Engine_NewTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).NewTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/NewTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).NewTx(ctx, req.(*NewTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Commit(ctx, req.(*CommitTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Cancel(ctx, req.(*CancelTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_BeginLockResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginLockResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).BeginLockResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/BeginLockResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).BeginLockResource(ctx, req.(*BeginLockResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_EndLockResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndLockResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).EndLockResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/EndLockResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).EndLockResource(ctx, req.(*EndLockResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_ResourceStatusChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceStatusChangedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).ResourceStatusChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/ResourceStatusChanged",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).ResourceStatusChanged(ctx, req.(*ResourceStatusChangedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_AttachAgent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AttachAgentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServer).AttachAgent(m, &engineAttachAgentServer{stream})
}

type Engine_AttachAgentServer interface {
	Send(*AgentCommandRequest) error
	grpc.ServerStream
}

type engineAttachAgentServer struct {
	grpc.ServerStream
}

func (x *engineAttachAgentServer) Send(m *AgentCommandRequest) error {
	return x.ServerStream.SendMsg(m)
}

var _Engine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tcc.Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTx",
			Handler:    _Engine_NewTx_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Engine_Commit_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Engine_Cancel_Handler,
		},
		{
			MethodName: "BeginLockResource",
			Handler:    _Engine_BeginLockResource_Handler,
		},
		{
			MethodName: "EndLockResource",
			Handler:    _Engine_EndLockResource_Handler,
		},
		{
			MethodName: "ResourceStatusChanged",
			Handler:    _Engine_ResourceStatusChanged_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachAgent",
			Handler:       _Engine_AttachAgent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tcc.proto",
}
