// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcc.proto

package tcc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxStatus int32

const (
	TxStatus_Created   TxStatus = 0
	TxStatus_Confirmed TxStatus = 1
	TxStatus_Canceled  TxStatus = 2
	TxStatus_Timeout   TxStatus = 3
)

var TxStatus_name = map[int32]string{
	0: "Created",
	1: "Confirmed",
	2: "Canceled",
	3: "Timeout",
}

var TxStatus_value = map[string]int32{
	"Created":   0,
	"Confirmed": 1,
	"Canceled":  2,
	"Timeout":   3,
}

func (x TxStatus) String() string {
	return proto.EnumName(TxStatus_name, int32(x))
}

func (TxStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{0}
}

type AgentCommand int32

const (
	AgentCommand_COMMMIT AgentCommand = 0
	AgentCommand_Cancel  AgentCommand = 1
)

var AgentCommand_name = map[int32]string{
	0: "COMMMIT",
	1: "Cancel",
}

var AgentCommand_value = map[string]int32{
	"COMMMIT": 0,
	"Cancel":  1,
}

func (x AgentCommand) String() string {
	return proto.EnumName(AgentCommand_name, int32(x))
}

func (AgentCommand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{1}
}

type NewTxRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTxRequest) Reset()         { *m = NewTxRequest{} }
func (m *NewTxRequest) String() string { return proto.CompactTextString(m) }
func (*NewTxRequest) ProtoMessage()    {}
func (*NewTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{0}
}

func (m *NewTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTxRequest.Unmarshal(m, b)
}
func (m *NewTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTxRequest.Marshal(b, m, deterministic)
}
func (m *NewTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTxRequest.Merge(m, src)
}
func (m *NewTxRequest) XXX_Size() int {
	return xxx_messageInfo_NewTxRequest.Size(m)
}
func (m *NewTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTxRequest proto.InternalMessageInfo

func (m *NewTxRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type NewTxResponse struct {
	Txid                 string   `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTxResponse) Reset()         { *m = NewTxResponse{} }
func (m *NewTxResponse) String() string { return proto.CompactTextString(m) }
func (*NewTxResponse) ProtoMessage()    {}
func (*NewTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{1}
}

func (m *NewTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTxResponse.Unmarshal(m, b)
}
func (m *NewTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTxResponse.Marshal(b, m, deterministic)
}
func (m *NewTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTxResponse.Merge(m, src)
}
func (m *NewTxResponse) XXX_Size() int {
	return xxx_messageInfo_NewTxResponse.Size(m)
}
func (m *NewTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTxResponse proto.InternalMessageInfo

func (m *NewTxResponse) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type CommitTxRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTxRequest) Reset()         { *m = CommitTxRequest{} }
func (m *CommitTxRequest) String() string { return proto.CompactTextString(m) }
func (*CommitTxRequest) ProtoMessage()    {}
func (*CommitTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{2}
}

func (m *CommitTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTxRequest.Unmarshal(m, b)
}
func (m *CommitTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTxRequest.Marshal(b, m, deterministic)
}
func (m *CommitTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTxRequest.Merge(m, src)
}
func (m *CommitTxRequest) XXX_Size() int {
	return xxx_messageInfo_CommitTxRequest.Size(m)
}
func (m *CommitTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTxRequest proto.InternalMessageInfo

func (m *CommitTxRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type CommitTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTxResponse) Reset()         { *m = CommitTxResponse{} }
func (m *CommitTxResponse) String() string { return proto.CompactTextString(m) }
func (*CommitTxResponse) ProtoMessage()    {}
func (*CommitTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{3}
}

func (m *CommitTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTxResponse.Unmarshal(m, b)
}
func (m *CommitTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTxResponse.Marshal(b, m, deterministic)
}
func (m *CommitTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTxResponse.Merge(m, src)
}
func (m *CommitTxResponse) XXX_Size() int {
	return xxx_messageInfo_CommitTxResponse.Size(m)
}
func (m *CommitTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTxResponse proto.InternalMessageInfo

type CancelTxRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTxRequest) Reset()         { *m = CancelTxRequest{} }
func (m *CancelTxRequest) String() string { return proto.CompactTextString(m) }
func (*CancelTxRequest) ProtoMessage()    {}
func (*CancelTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{4}
}

func (m *CancelTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTxRequest.Unmarshal(m, b)
}
func (m *CancelTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTxRequest.Marshal(b, m, deterministic)
}
func (m *CancelTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTxRequest.Merge(m, src)
}
func (m *CancelTxRequest) XXX_Size() int {
	return xxx_messageInfo_CancelTxRequest.Size(m)
}
func (m *CancelTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTxRequest proto.InternalMessageInfo

func (m *CancelTxRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type CancelTxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTxResponse) Reset()         { *m = CancelTxResponse{} }
func (m *CancelTxResponse) String() string { return proto.CompactTextString(m) }
func (*CancelTxResponse) ProtoMessage()    {}
func (*CancelTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{5}
}

func (m *CancelTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTxResponse.Unmarshal(m, b)
}
func (m *CancelTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTxResponse.Marshal(b, m, deterministic)
}
func (m *CancelTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTxResponse.Merge(m, src)
}
func (m *CancelTxResponse) XXX_Size() int {
	return xxx_messageInfo_CancelTxResponse.Size(m)
}
func (m *CancelTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTxResponse proto.InternalMessageInfo

type BeforeRequireRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Agent                string   `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Resource             string   `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeforeRequireRequest) Reset()         { *m = BeforeRequireRequest{} }
func (m *BeforeRequireRequest) String() string { return proto.CompactTextString(m) }
func (*BeforeRequireRequest) ProtoMessage()    {}
func (*BeforeRequireRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{6}
}

func (m *BeforeRequireRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeforeRequireRequest.Unmarshal(m, b)
}
func (m *BeforeRequireRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeforeRequireRequest.Marshal(b, m, deterministic)
}
func (m *BeforeRequireRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeforeRequireRequest.Merge(m, src)
}
func (m *BeforeRequireRequest) XXX_Size() int {
	return xxx_messageInfo_BeforeRequireRequest.Size(m)
}
func (m *BeforeRequireRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeforeRequireRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeforeRequireRequest proto.InternalMessageInfo

func (m *BeforeRequireRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *BeforeRequireRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *BeforeRequireRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *BeforeRequireRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type BeforeRequireRespose struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeforeRequireRespose) Reset()         { *m = BeforeRequireRespose{} }
func (m *BeforeRequireRespose) String() string { return proto.CompactTextString(m) }
func (*BeforeRequireRespose) ProtoMessage()    {}
func (*BeforeRequireRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{7}
}

func (m *BeforeRequireRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeforeRequireRespose.Unmarshal(m, b)
}
func (m *BeforeRequireRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeforeRequireRespose.Marshal(b, m, deterministic)
}
func (m *BeforeRequireRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeforeRequireRespose.Merge(m, src)
}
func (m *BeforeRequireRespose) XXX_Size() int {
	return xxx_messageInfo_BeforeRequireRespose.Size(m)
}
func (m *BeforeRequireRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_BeforeRequireRespose.DiscardUnknown(m)
}

var xxx_messageInfo_BeforeRequireRespose proto.InternalMessageInfo

type AfterRequireRequest struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Agent                string   `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Resource             string   `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AfterRequireRequest) Reset()         { *m = AfterRequireRequest{} }
func (m *AfterRequireRequest) String() string { return proto.CompactTextString(m) }
func (*AfterRequireRequest) ProtoMessage()    {}
func (*AfterRequireRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{8}
}

func (m *AfterRequireRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AfterRequireRequest.Unmarshal(m, b)
}
func (m *AfterRequireRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AfterRequireRequest.Marshal(b, m, deterministic)
}
func (m *AfterRequireRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AfterRequireRequest.Merge(m, src)
}
func (m *AfterRequireRequest) XXX_Size() int {
	return xxx_messageInfo_AfterRequireRequest.Size(m)
}
func (m *AfterRequireRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AfterRequireRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AfterRequireRequest proto.InternalMessageInfo

func (m *AfterRequireRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *AfterRequireRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *AfterRequireRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *AfterRequireRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type AfterRequireRespose struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AfterRequireRespose) Reset()         { *m = AfterRequireRespose{} }
func (m *AfterRequireRespose) String() string { return proto.CompactTextString(m) }
func (*AfterRequireRespose) ProtoMessage()    {}
func (*AfterRequireRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{9}
}

func (m *AfterRequireRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AfterRequireRespose.Unmarshal(m, b)
}
func (m *AfterRequireRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AfterRequireRespose.Marshal(b, m, deterministic)
}
func (m *AfterRequireRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AfterRequireRespose.Merge(m, src)
}
func (m *AfterRequireRespose) XXX_Size() int {
	return xxx_messageInfo_AfterRequireRespose.Size(m)
}
func (m *AfterRequireRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_AfterRequireRespose.DiscardUnknown(m)
}

var xxx_messageInfo_AfterRequireRespose proto.InternalMessageInfo

type AgentCommandRequest struct {
	Txid                 string       `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Resource             string       `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Command              AgentCommand `protobuf:"varint,3,opt,name=command,proto3,enum=tcc.AgentCommand" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AgentCommandRequest) Reset()         { *m = AgentCommandRequest{} }
func (m *AgentCommandRequest) String() string { return proto.CompactTextString(m) }
func (*AgentCommandRequest) ProtoMessage()    {}
func (*AgentCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{10}
}

func (m *AgentCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentCommandRequest.Unmarshal(m, b)
}
func (m *AgentCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentCommandRequest.Marshal(b, m, deterministic)
}
func (m *AgentCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentCommandRequest.Merge(m, src)
}
func (m *AgentCommandRequest) XXX_Size() int {
	return xxx_messageInfo_AgentCommandRequest.Size(m)
}
func (m *AgentCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentCommandRequest proto.InternalMessageInfo

func (m *AgentCommandRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *AgentCommandRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *AgentCommandRequest) GetCommand() AgentCommand {
	if m != nil {
		return m.Command
	}
	return AgentCommand_COMMMIT
}

type AttachAgentRequest struct {
	Agent                string   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachAgentRequest) Reset()         { *m = AttachAgentRequest{} }
func (m *AttachAgentRequest) String() string { return proto.CompactTextString(m) }
func (*AttachAgentRequest) ProtoMessage()    {}
func (*AttachAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35dc7e9ebe8c6643, []int{11}
}

func (m *AttachAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachAgentRequest.Unmarshal(m, b)
}
func (m *AttachAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachAgentRequest.Marshal(b, m, deterministic)
}
func (m *AttachAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachAgentRequest.Merge(m, src)
}
func (m *AttachAgentRequest) XXX_Size() int {
	return xxx_messageInfo_AttachAgentRequest.Size(m)
}
func (m *AttachAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachAgentRequest proto.InternalMessageInfo

func (m *AttachAgentRequest) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func init() {
	proto.RegisterEnum("tcc.TxStatus", TxStatus_name, TxStatus_value)
	proto.RegisterEnum("tcc.AgentCommand", AgentCommand_name, AgentCommand_value)
	proto.RegisterType((*NewTxRequest)(nil), "tcc.NewTxRequest")
	proto.RegisterType((*NewTxResponse)(nil), "tcc.NewTxResponse")
	proto.RegisterType((*CommitTxRequest)(nil), "tcc.CommitTxRequest")
	proto.RegisterType((*CommitTxResponse)(nil), "tcc.CommitTxResponse")
	proto.RegisterType((*CancelTxRequest)(nil), "tcc.CancelTxRequest")
	proto.RegisterType((*CancelTxResponse)(nil), "tcc.CancelTxResponse")
	proto.RegisterType((*BeforeRequireRequest)(nil), "tcc.BeforeRequireRequest")
	proto.RegisterType((*BeforeRequireRespose)(nil), "tcc.BeforeRequireRespose")
	proto.RegisterType((*AfterRequireRequest)(nil), "tcc.AfterRequireRequest")
	proto.RegisterType((*AfterRequireRespose)(nil), "tcc.AfterRequireRespose")
	proto.RegisterType((*AgentCommandRequest)(nil), "tcc.AgentCommandRequest")
	proto.RegisterType((*AttachAgentRequest)(nil), "tcc.AttachAgentRequest")
}

func init() { proto.RegisterFile("tcc.proto", fileDescriptor_35dc7e9ebe8c6643) }

var fileDescriptor_35dc7e9ebe8c6643 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xd1, 0x8f, 0xd2, 0x40,
	0x10, 0xc6, 0xaf, 0x70, 0xc7, 0xc1, 0x1c, 0x68, 0x9d, 0xe3, 0x14, 0x1b, 0x63, 0x4c, 0x8d, 0xd1,
	0x60, 0xc2, 0x99, 0x33, 0xfe, 0x01, 0x40, 0xee, 0xc1, 0x07, 0x34, 0x39, 0x79, 0xf2, 0xad, 0xb7,
	0x1d, 0xa0, 0x39, 0xbb, 0x8b, 0xdb, 0x69, 0x0e, 0xff, 0x70, 0xdf, 0x4d, 0x77, 0x29, 0x2e, 0x05,
	0xf1, 0xed, 0x9e, 0x68, 0x77, 0xbe, 0xef, 0x9b, 0x59, 0xe6, 0x97, 0x42, 0x8b, 0x85, 0x18, 0x2c,
	0xb5, 0x62, 0x85, 0x75, 0x16, 0x22, 0x0c, 0xa1, 0xfd, 0x85, 0xee, 0xa7, 0xab, 0x1b, 0xfa, 0x99,
	0x53, 0xc6, 0x88, 0x70, 0xcc, 0xab, 0x24, 0xee, 0x79, 0xaf, 0xbc, 0x77, 0xad, 0x1b, 0xf3, 0x1c,
	0xbe, 0x86, 0xce, 0x5a, 0x93, 0x2d, 0x95, 0xcc, 0x68, 0x23, 0xaa, 0x39, 0xa2, 0x37, 0xf0, 0x78,
	0xac, 0xd2, 0x34, 0xe1, 0xc3, 0x59, 0x08, 0xfe, 0x5f, 0x99, 0x8d, 0x33, 0xd6, 0x48, 0x0a, 0xfa,
	0xf1, 0x7f, 0xeb, 0x46, 0xb6, 0xb6, 0x4a, 0xe8, 0x8e, 0x68, 0xa6, 0x34, 0x15, 0xc6, 0xc4, 0xfe,
	0xfc, 0xc3, 0x8f, 0x5d, 0x38, 0x89, 0xe6, 0x24, 0x79, 0x3d, 0xb6, 0x7d, 0xc1, 0x00, 0x9a, 0x9a,
	0x32, 0x95, 0x6b, 0x41, 0xbd, 0xba, 0x29, 0x6c, 0xde, 0xd1, 0x87, 0xfa, 0x1d, 0xfd, 0xea, 0x1d,
	0x9b, 0xe3, 0xe2, 0x31, 0x7c, 0xba, 0xd3, 0x2f, 0x5b, 0xaa, 0x8c, 0xc2, 0x14, 0xce, 0x87, 0x33,
	0x26, 0xfd, 0x40, 0x63, 0x5c, 0x54, 0xdb, 0xd9, 0x29, 0x34, 0x9c, 0x0f, 0x8b, 0xb4, 0xe2, 0x1f,
	0x8e, 0x64, 0x7c, 0x68, 0x0a, 0xb7, 0x5f, 0xad, 0xd2, 0xef, 0x3d, 0x9c, 0x0a, 0x9b, 0x60, 0x46,
	0x79, 0x74, 0xf5, 0x64, 0x50, 0x50, 0xb3, 0x15, 0x5d, 0x2a, 0xc2, 0x3e, 0xe0, 0x90, 0x39, 0x12,
	0x0b, 0x53, 0x2e, 0x5b, 0x6e, 0x2e, 0xe9, 0x39, 0x97, 0xec, 0x0f, 0xa1, 0x39, 0x5d, 0x7d, 0xe3,
	0x88, 0xf3, 0x0c, 0xcf, 0xe0, 0x74, 0xac, 0x29, 0x62, 0x8a, 0xfd, 0x23, 0xec, 0x40, 0x6b, 0xac,
	0xe4, 0x2c, 0xd1, 0x29, 0xc5, 0xbe, 0x87, 0x6d, 0x68, 0xda, 0x4d, 0x53, 0xec, 0xd7, 0x0a, 0xe5,
	0x34, 0x49, 0x49, 0xe5, 0xec, 0xd7, 0xfb, 0x6f, 0xa1, 0xed, 0xce, 0x61, 0x62, 0xbe, 0x4e, 0x26,
	0x93, 0xcf, 0x53, 0xff, 0x08, 0x01, 0x1a, 0xd6, 0xe7, 0x7b, 0x57, 0xbf, 0x6b, 0xd0, 0xb8, 0x96,
	0xf3, 0x44, 0x12, 0x0e, 0xe0, 0xc4, 0xf0, 0x8b, 0xf6, 0x1e, 0x2e, 0xef, 0x01, 0xba, 0x47, 0x6b,
	0xbc, 0x3f, 0x41, 0xc3, 0x32, 0x8a, 0x5d, 0x53, 0xad, 0x70, 0x1d, 0x5c, 0x54, 0x4e, 0x1d, 0x9b,
	0xe9, 0x5e, 0xda, 0xb6, 0x99, 0x2e, 0x6d, 0x15, 0x84, 0xf1, 0x1a, 0x3a, 0x5b, 0x48, 0xe1, 0x73,
	0xa3, 0xdb, 0x87, 0x75, 0xb0, 0xb7, 0x64, 0x76, 0x8f, 0x23, 0x68, 0xbb, 0x48, 0x60, 0xcf, 0xee,
	0x6c, 0x17, 0xca, 0x60, 0x5f, 0xa5, 0xcc, 0x38, 0x73, 0x76, 0x89, 0xcf, 0xac, 0x70, 0x67, 0xbb,
	0x65, 0xc2, 0x2e, 0x6a, 0x1f, 0xbc, 0xd1, 0xcb, 0xef, 0x2f, 0xe6, 0x09, 0x2f, 0xf2, 0xdb, 0x81,
	0x50, 0xe9, 0xe5, 0x5c, 0xa5, 0x94, 0x2d, 0x24, 0xf1, 0xbd, 0xd2, 0x77, 0x97, 0x2c, 0xc4, 0x6d,
	0xc3, 0x7c, 0x7c, 0x3e, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xad, 0x58, 0x2f, 0x92, 0x89, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EngineClient is the client API for Engine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EngineClient interface {
	NewTx(ctx context.Context, in *NewTxRequest, opts ...grpc.CallOption) (*NewTxResponse, error)
	Commit(ctx context.Context, in *CommitTxRequest, opts ...grpc.CallOption) (*CommitTxResponse, error)
	Cancel(ctx context.Context, in *CancelTxRequest, opts ...grpc.CallOption) (*CancelTxResponse, error)
	BeforeRequire(ctx context.Context, in *BeforeRequireRequest, opts ...grpc.CallOption) (*BeforeRequireRespose, error)
	AfterRequire(ctx context.Context, in *AfterRequireRequest, opts ...grpc.CallOption) (*AfterRequireRespose, error)
	AttachAgent(ctx context.Context, in *AttachAgentRequest, opts ...grpc.CallOption) (Engine_AttachAgentClient, error)
}

type engineClient struct {
	cc *grpc.ClientConn
}

func NewEngineClient(cc *grpc.ClientConn) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) NewTx(ctx context.Context, in *NewTxRequest, opts ...grpc.CallOption) (*NewTxResponse, error) {
	out := new(NewTxResponse)
	err := c.cc.Invoke(ctx, "/tcc.Engine/NewTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Commit(ctx context.Context, in *CommitTxRequest, opts ...grpc.CallOption) (*CommitTxResponse, error) {
	out := new(CommitTxResponse)
	err := c.cc.Invoke(ctx, "/tcc.Engine/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Cancel(ctx context.Context, in *CancelTxRequest, opts ...grpc.CallOption) (*CancelTxResponse, error) {
	out := new(CancelTxResponse)
	err := c.cc.Invoke(ctx, "/tcc.Engine/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) BeforeRequire(ctx context.Context, in *BeforeRequireRequest, opts ...grpc.CallOption) (*BeforeRequireRespose, error) {
	out := new(BeforeRequireRespose)
	err := c.cc.Invoke(ctx, "/tcc.Engine/BeforeRequire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) AfterRequire(ctx context.Context, in *AfterRequireRequest, opts ...grpc.CallOption) (*AfterRequireRespose, error) {
	out := new(AfterRequireRespose)
	err := c.cc.Invoke(ctx, "/tcc.Engine/AfterRequire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) AttachAgent(ctx context.Context, in *AttachAgentRequest, opts ...grpc.CallOption) (Engine_AttachAgentClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Engine_serviceDesc.Streams[0], "/tcc.Engine/AttachAgent", opts...)
	if err != nil {
		return nil, err
	}
	x := &engineAttachAgentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Engine_AttachAgentClient interface {
	Recv() (*AgentCommandRequest, error)
	grpc.ClientStream
}

type engineAttachAgentClient struct {
	grpc.ClientStream
}

func (x *engineAttachAgentClient) Recv() (*AgentCommandRequest, error) {
	m := new(AgentCommandRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EngineServer is the server API for Engine service.
type EngineServer interface {
	NewTx(context.Context, *NewTxRequest) (*NewTxResponse, error)
	Commit(context.Context, *CommitTxRequest) (*CommitTxResponse, error)
	Cancel(context.Context, *CancelTxRequest) (*CancelTxResponse, error)
	BeforeRequire(context.Context, *BeforeRequireRequest) (*BeforeRequireRespose, error)
	AfterRequire(context.Context, *AfterRequireRequest) (*AfterRequireRespose, error)
	AttachAgent(*AttachAgentRequest, Engine_AttachAgentServer) error
}

func RegisterEngineServer(s *grpc.Server, srv EngineServer) {
	s.RegisterService(&_Engine_serviceDesc, srv)
}

func _Engine_NewTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).NewTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/NewTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).NewTx(ctx, req.(*NewTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Commit(ctx, req.(*CommitTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Cancel(ctx, req.(*CancelTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_BeforeRequire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforeRequireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).BeforeRequire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/BeforeRequire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).BeforeRequire(ctx, req.(*BeforeRequireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_AfterRequire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterRequireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).AfterRequire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tcc.Engine/AfterRequire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).AfterRequire(ctx, req.(*AfterRequireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_AttachAgent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AttachAgentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServer).AttachAgent(m, &engineAttachAgentServer{stream})
}

type Engine_AttachAgentServer interface {
	Send(*AgentCommandRequest) error
	grpc.ServerStream
}

type engineAttachAgentServer struct {
	grpc.ServerStream
}

func (x *engineAttachAgentServer) Send(m *AgentCommandRequest) error {
	return x.ServerStream.SendMsg(m)
}

var _Engine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tcc.Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTx",
			Handler:    _Engine_NewTx_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Engine_Commit_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Engine_Cancel_Handler,
		},
		{
			MethodName: "BeforeRequire",
			Handler:    _Engine_BeforeRequire_Handler,
		},
		{
			MethodName: "AfterRequire",
			Handler:    _Engine_AfterRequire_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachAgent",
			Handler:       _Engine_AttachAgent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tcc.proto",
}
